<?php

namespace App\Repositories;

use App\Models\Coupon;

class CouponRepository extends AbstractRepository
{

    public function getModel()
    {
        return Coupon::class;
    }

    public function getAll($request, $limit = null)
    {
        $query = Coupon::query();
        if ($query) {
            $query->orderBy($request['column'], $request['sort']);
        }
        return $query->where('status', 1)->paginate($limit);
    }

    public function create($attributes, int $id = null)
    {
        return parent::create($attributes, $id);
    }

    public function find($id)
    {
        return parent::find($id); // TODO: Change the autogenerated stub
    }

    public function update($id, array $attributes)
    {
        return parent::update($id, $attributes); // TODO: Change the autogenerated stub
    }

    public function delete($id)
    {
        return parent::delete($id); // TODO: Change the autogenerated stub
    }
}
